consolidate exit codes

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -107,17 +107,28 @@ runs:
           run: dotnet tool install pkgchk-cli --version 0.3.558-preview --local  --create-manifest-if-needed
           
         - name: Scan for vulnerabilities
+          id: scanVulnerabilities
           shell: bash          
           if: ${{ inputs.scan-issues == 'true' }}
-          continue-on-error: true
+          continue-on-error: true # TODO: this causes the overall flow to NOT be marked as failed.
           run: |
             dotnet pkgchk scan ./${{ inputs.project-path }} --deprecated ${{ inputs.deprecated }} --vulnerable ${{ inputs.vulnerable }} --transitive ${{ inputs.transitives }} --trace ${{ inputs.trace }} --github-token ${{ inputs.github-token }} --github-repo ${{ inputs.repo }}  --github-commit ${{ inputs.commit-hash }} --github-title "${{ inputs.github-title }}" --pass-img "${{ inputs.pass-img }}" --fail-img "${{ inputs.fail-img }}"  --github-pr "${{ inputs.prid }}" -s "${{ inputs.fail-on-critical == 'true' && 'Critical' || ' ' }}" -s "${{ inputs.fail-on-high == 'true' && 'High' || ' ' }}" -s "${{ inputs.fail-on-moderate == 'true' && 'Moderate' || ' ' }}" -s "${{ inputs.fail-on-critical == 'true' && 'Critical Bugs' || ' ' }}"  -s "${{ inputs.fail-on-legacy == 'true' && 'Legacy' || ' ' }}"
 
         - name: Scan for upgrades
+          id: scanUpgrades
           shell: bash          
           if: ${{ inputs.scan-upgrades == 'true' }}
+          continue-on-error: true # TODO: this causes the overall flow to NOT be marked as failed.
           run: |
             dotnet pkgchk upgrades ./${{ inputs.project-path }} --trace ${{ inputs.trace }} --github-token ${{ inputs.github-token }} --github-repo ${{ inputs.repo }}  --github-commit ${{ inputs.commit-hash }} --github-title "${{ inputs.github-upgrade-title }}" --pass-img "${{ inputs.pass-img }}" --fail-img "${{ inputs.fail-img }}"  --github-pr "${{ inputs.prid }}" --break-on-upgrades "${{ inputs.fail-on-upgrades }}"
+
+        - name: Consolidate results
+          if : steps.scanVulnerabilities.outcome == 'failure'
+          run: exit 1
+
+        - name: Consolidate results
+          if : steps.scanUpgrades.outcome == 'failure'
+          run: exit 1
 
 branding:
   icon: 'shield'
